apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: poc-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: poc-server
  minReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50